airflow_db:
  target: dev
  outputs:
    dev:
      type: postgres
      host: host.docker.internal
      user: airflow
      password: airflow
      port: 8585
      dbname: postgres
      schema: public
      threads: 4